# 设置微服务的名称
spring:
  application:
    name: product-data-service
  zipkin:
    #base-url: http://192.168.11.129:9411
    base-url: http://localhost:9411

# 设置注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
     # defaultZone: http://192.168.11.129:8761/eureka
      #defaultZone: http://183.193.36.254:8761/eureka
