spring:
  application:
    name: product-turbine
eureka:
  client:
    service-url:
      #defaultZone: http://192.168.11.129:8761/eureka
      defaultZone: http://localhost:8761/eureka

turbine:
  aggregator:
    cluster-config: default
  appConfig: product-view-service-feign
  clusterNameExpression: new String("default")


