spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wanglichaoya/SpringCloudConfig-20191016/
          search-paths: src
eureka:
  client:
    service-url:
      #defaultzone: http://192.168.11.129:8761/eureka/
      defaultzone: http://localhost:8761/eureka/