spring:
  application:
    name: product-view-service-feign
    #配置链路追踪
  zipkin:
    #base-url: http://192.168.11.129:9411
    base-url: http://localhost:9411


 # 为了访问 /actuator/bus-refresh，设置下面的内容
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

#启动断路器
feign.hystrix.enabled: true
